# Configuration for the UI BFF Go service

http:
  listen_address: "0.0.0.0:8080"

grpc_backends:
  backtester_address: "localhost:50055"
  risk_management_address: "localhost:50056"
  data_ingestion_address: "localhost:50052"
  # **NEW:** Add address for the Infrastructure service (Config/Discovery)
  infrastructure_address: "localhost:50060"

default_account_id: "trading_account_1"

# Add other BFF config here