// src/routes/status/+page.ts
import { graphqlClient } from '$lib/graphql/client';
import { GetSystemStatusDocument } from '$lib/graphql/generated/graphql'; // Generated by graphql-codegen
import type { PageLoad } from './$types';

export const load: PageLoad = async ({ fetch }) => {
  try {
    // Fetch system status data from the GraphQL endpoint
    const data = await graphqlClient.request(GetSystemStatusDocument);

    // data will contain { systemStatus: ServiceStatus[] }

    return {
      systemStatus: data.systemStatus,
      error: null
    };
  } catch (error) {
    console.error('Error fetching system status:', error);
    return {
      systemStatus: [],
      error: 'Failed to load system status.'
    };
  }
};

/*
Note:
You will need to run `npm run graphql-codegen` again after creating `status.graphql`.
Update `codegen.yml` to ensure it picks up this new query file.
*/