name = "MLEngine"
uuid = uuid = "0b15a152-0e73-4991-b627-14197670c46c"
authors = ["Nick <nikolas.spyridonidis@gmail.com>"]
version = "0.1.0"

[deps]
gRPC = "..."       # <--- REPLACE THIS WITH THE UUID FOR gRPC.jl
ProtoBuf = "..."   # <--- REPLACE THIS WITH THE UUID FOR ProtoBuf.jl
YAML = "..."       # <--- REPLACE THIS WITH THE UUID FOR YAML.jl
Dates = "..."      # Standard library (no UUID needed in deps)
CircularArrays = "..." # <--- REPLACE THIS WITH THE UUID FOR CircularArrays.jl
DataFrames = "..." # <--- REPLACE THIS WITH THE UUID FOR DataFrames.jl
Flux = "..."       # <--- REPLACE THIS WITH THE UUID FOR Flux.jl
CUDA = "..."       # <--- REPLACE THIS WITH THE UUID FOR CUDA.jl (Optional if not using GPU)
NNlib = "..."      # <--- REPLACE THIS WITH THE UUID FOR NNlib.jl
BSON = "..."       # <--- REPLACE THIS WITH THE UUID FOR BSON.jl
HTTP = "..."       # <--- REPLACE THIS WITH THE UUID FOR HTTP.jl
Logging = "..."    # Standard library (no UUID needed in deps)
JSON = "..."       # <--- REPLACE THIS WITH THE UUID FOR JSON.jl
ArgParse = "..."   # <--- REPLACE THIS WITH THE UUID FOR ArgParse.jl
FileWatching = "..." # Standard library (no UUID needed in deps)
SignalInterrupt = "..." # <--- REPLACE THIS WITH THE UUID FOR SignalInterrupt.jl
Statistics = "..." # Standard library (no UUID needed in deps)
Random = "     # Standard library (no UUID needed in deps) # Added for shuffling
Base64 =      # Standard library (no UUID needed in deps) # Might be needed by ProtoBuf/gRPC


[compat]
julia = "1.9" # Or your target Julia version

# Add any test dependencies in a [extras] and [targets] section if needed
# [extras]
# Test = "..." # UUID for the built-in Test stdlib

# [targets]
# test = ["Test"]