# Configuration for the Strategy DSL Engine

# gRPC configuration for this service (serving the StrategyEngineService RPCs)
grpc:
  listen_address: "0.0.0.0:50053" # Address where this service listens for ReloadStrategies RPC etc.

# Addresses for upstream gRPC services
upstream_grpc:
  indicator_engine_address: "localhost:50051" # Address of the Indicator Engine gRPC server
  ml_engine_address: "localhost:50052" # Address of the ML Engine gRPC server
  data_ingestion_address: "localhost:50050" # Address of the Data Ingestion gRPC server (for order execution)

# Configuration for strategy execution
strategy_engine:
  # Path to the directory containing strategy files (*.strat)
  # This is where the strategy-gen-lisp component will place generated strategies
  strategies_path: "examples" # Or specify a dedicated directory like "generated_strategies"
  # List of strategy files to load and run (relative to strategies_path).
  # When ReloadStrategies RPC is called, this list is re-read.
  active_strategies:
    - simple_ma_crossover.strat
    - prediction_threshold.strat
    # Add names of generated strategies here or manage the file list dynamically

# Data management configuration
data:
  # Maximum number of recent indicator/prediction values to store per item.
  # Set this to at least 2 if using the '.prev' syntax in strategies.
  max_history_size: 10 # Store enough history for '.prev' and potential future extensions

# Health check and Prometheus metrics configuration
health_check:
  listen_address: "0.0.0.0:8082" # Address for the HTTP health check (/healthz) and Prometheus (/metrics) server

# Optional: Logging configuration
logging:
  level: "Debug" # Debug, Info, Warning, Error, App